title: Sun Yafeng
url: "https://sunyafeng1996.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/sunyafeng1996"
footer_text: "Page copyright@ Junhong Huang"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "首页"
   link: "/"
 - name: "研究兴趣"
   link: "interest"
 - name: "Contact"
   link: "contact"
